name: "cabal"

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  cabal:
    strategy:
      fail-fast: false
      matrix:
        ghc:
          - "9.2.7"
          - "9.4.4"
        platform:
          - os: "macos-latest"
            set-env: "export"
          - os: "ubuntu-latest"
            set-env: "export"
          - os: "windows-latest"
            set-env: "set"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3.3.0

      - uses: haskell/actions/setup@v2.3.4
        with:
          ghc-version: ${{ matrix.ghc }}

      - name: Compile
        run: cabal build

      - name: Unit Tests
        run: cabal test unit

      - name: Functional Tests
        run: |
          ${{ matrix.platform.set-env }} RUN_FUNC=1
          cabal test functional